### ISSUE TITLE
Updates for latest firmware

### ISSUE THREAD

**Issue by HalosGhost** [MarSoft/pebble_firmware_patches#11]
The latest Pebble firmware is now v3.4. Any chance of an update for the patches (particularly AppDisabler)? I just got my PTS and generally want to use it as a watch that I can code for (*not* a watch that is always connected to my phone); so I'd love to be able to remove/disable the built-in apps that only function when connected to my phone (namely the weather, notifications and music applications) along with the default watchface that I do not want (tictoc).

**Comment by MarSoft** [comment]
They majorly reworked the codebase, so right now I don't plan to update that appdisabler patch. Maybe later.. For now you could just move these apps to the end of menu, although I understand it is not a solution.

**Comment by HalosGhost** [comment]
That's incredibly unfortunate to hear. As I mentioned above, I'm really not interested in using the phone connection ever (other than for my own app development) after I have the watch set up to my liking, so needing the phone connection to rearrange apps is a bummer. Can you point me to the documentation or tools you used to figure out how to create the patch yourself so that I might be able to engineer one for the latest version?

**Comment by iddq** [comment]
I'm just wondering is the firmware not opensource?

**Comment by MarSoft** [comment]
No, firmware is proprietary, and it uses some proprietary libraries like
bluetopia. So we have to reverse-engineer it.
For tools used - they are disassembler like IDA and also toolkit at
http://github.com/MarSoft/pebble-firmware-utils/ .

чт, 7 янв. 2016 г. в 21:09, iddq <notifications@github.com>:

**Comment by HalosGhost** [comment]
Has there been any renewed interest in this? As the firmware has progressed, more and more system apps are being added (the opposite of what I want); I would love to be able to remove some of them.

**Comment by MarSoft** [comment]
Hello. I just implemented new variant of AppDisabler patch, for 3.x firmwares. You can apply it yourself. Don't forget to specify disable_* definitions:
```
patcher.py -A -o patched.bin ../patches/AppDisabler_392.pbp -D disable_tictoc -D disable_health -D disable_sendtext
```
You can see complete list in the patch file.
