### ISSUE TITLE
patcher fails with "No Suitable Range…"

### ISSUE THREAD

**Issue by HalosGhost** [MarSoft/pebble_firmware_patches#12]
This was attempted using the `AppDisabler_392.pbp` with the following `#define`s:

``` c
#define disable_music
#define disable_notifications
#define disable_health
#define disable_sendtext
```

running against the latest version (3.10.1 at the time of issue-open) of the `snowy_s3` firmware.

I received the following output:

``` console
$ ../patcher.py -o tintin_fw.bin.new AppDisabler_392.pbp
```

``` python
Loading files:
AppDisabler_392.pbp
Binding patches:
<patch:#library, 0 blocks>
<patch:AppDisabler_392.pbp, 3 blocks>
Traceback (most recent call last):
  File "../patcher.py", line 81, in <module>
    patch_fw(args)
  File "../patcher.py", line 66, in patch_fw
    p.bindall(data, ranges, args.codebase)
  File "/home/halosghost/prj/pebble-firmware-utils/libpatcher/patch.py", line 61, in bindall
    position = block.getPosition(binary, ranges)
  File "/home/halosghost/prj/pebble-firmware-utils/libpatcher/block.py", line 45, in getPosition
    r = ranges.find(self.getSize())
  File "/home/halosghost/prj/pebble-firmware-utils/libpatcher/ranges.py", line 82, in find
    raise RangeError("No suitable range for %d bytes (align: %d)" % (size,aligned))
libpatcher.ranges.RangeError: No suitable range for 30 bytes (align: 2)
```

Note that my local version of `python2` is 2.7.11.

Any idea what went wrong / is there any more information that would be helpful for you to have?

Thank you so much for your work! I am incredibly excited to have my watch's firmware a little more streamlined!

**Comment by MarSoft** [comment]
Just use patcher options.
For 2.x firmwares you would use -a to allow appending code to binary's end;
for 3.x use -A to do the same without size checking (which is currently not
functional).
Also you can use -D to specify defines in command line.

чт, 31 марта 2016, 16:31 Sam Stuewe <notifications@github.com>:

**Comment by HalosGhost** [comment]
Ahh, I did not realize ``-A`` was needed. seems to be going okay. I will try to flash my watch tonight and see how it goes!
